apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bank-api.fullname" . }}
  labels:
    {{- include "bank-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bank-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bank-api.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "bank-api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BANK_POSTGRES_HOST
              value: "{{ include "bank-api.fullname" . }}-postgresql:{{ .Values.postgresql.primary.service.port }}"
            - name: BANK_POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: BANK_POSTGRES_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: BANK_POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: BANK_POSTGRES_SSLMODE
              value: "disable"
            - name: BANK_POSTGRES_AUTOMIGRATE
              value: "true"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 